/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prysumadosnumeros;

/**
 *
 * @author Sophie
 */
public class PantallaSuma extends javax.swing.JFrame {

    /**
     * Creates new form PantallaSuma
     */
    public PantallaSuma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_numeroUno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_numeroDos = new javax.swing.JTextField();
        boton1 = new javax.swing.JButton();
        lbl_resultado = new javax.swing.JLabel();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BIENVENIDOS A MI SUPER PROGRAMA DE SUMA");

        jLabel2.setText("INGRESE NUMERO UNO:");

        jLabel3.setText("INGRESE NUMERO DOS:");

        boton1.setText("SUMA");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumar(evt);
            }
        });

        lbl_resultado.setText("0.00");

        boton2.setText("RESTA");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resta(evt);
            }
        });

        boton3.setText("MULTIPLICACION");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacion(evt);
            }
        });

        boton4.setText("DIVISION");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                division(evt);
            }
        });

        boton5.setText("VERIFICAR PAR/IMPAR");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parimpar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txt_numeroUno, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(txt_numeroDos)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton3))
                            .addComponent(lbl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton5)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_numeroUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_numeroDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton1)
                    .addComponent(boton2)
                    .addComponent(boton3)
                    .addComponent(boton4)
                    .addComponent(boton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_resultado)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sumar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumar
       double numeroUno = Double.parseDouble(txt_numeroUno.getText());
       double numeroDos = Double.parseDouble(txt_numeroDos.getText());
       double resultado=numeroUno+numeroDos;
       lbl_resultado.setText(Double.toString(resultado));
       
    }//GEN-LAST:event_sumar

    private void multiplicacion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacion
        double numeroUno = Double.parseDouble(txt_numeroUno.getText());
       double numeroDos = Double.parseDouble(txt_numeroDos.getText());
       double resultado=numeroUno*numeroDos;
       lbl_resultado.setText(Double.toString(resultado));
    }//GEN-LAST:event_multiplicacion

    private void resta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resta
       double numeroUno = Double.parseDouble(txt_numeroUno.getText());
       double numeroDos = Double.parseDouble(txt_numeroDos.getText());
       double resultado=numeroUno-numeroDos;
       lbl_resultado.setText(Double.toString(resultado));
    }//GEN-LAST:event_resta

    private void division(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_division
       double numeroUno = Double.parseDouble(txt_numeroUno.getText());
       double numeroDos = Double.parseDouble(txt_numeroDos.getText());
       double resultado=numeroUno/numeroDos;
       lbl_resultado.setText(Double.toString(resultado));
    }//GEN-LAST:event_division

    private void parimpar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parimpar
       // Obtener el resultado desde el JLabel lbl_resultado
    double resultado;

    try {
        // Intentar obtener el número desde el texto del JLabel
        resultado = Double.parseDouble(lbl_resultado.getText());

        // Verificar si el resultado es un número entero (sin decimales)
        if (resultado % 1 == 0) {
            // Convertir el resultado a un número entero
            int numero = (int) resultado;

            // Verificar si el número es par o impar
            if (numero % 2 == 0) {
                lbl_resultado.setText("El número es par");
            } else {
                lbl_resultado.setText("El número es impar");
            }
        } else {
            lbl_resultado.setText("El resultado no es un número entero");
        }
    } catch (NumberFormatException e) {
        // Si hay un error al convertir el texto a número, mostrar mensaje de error
        lbl_resultado.setText("Error: No es un número válido");
    }
    }//GEN-LAST:event_parimpar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaSuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaSuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaSuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaSuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaSuma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JTextField txt_numeroDos;
    private javax.swing.JTextField txt_numeroUno;
    // End of variables declaration//GEN-END:variables
}
